<script type="text/javascript" src="js/jquery-3.1.1.min.js"></script>    
    <script type="text/javascript" src="js/bootstrap.min.js"></script>
    <script type="text/javascript" src="js/angular.min.js"></script>
    <script type="text/javascript" src="js/prefixfree.min.js"></script>
    <script type="text/javascript" src="js/app.js"></script>
    <script type="text/javascript" src="js/admin.js"></script>
    <script type="text/javascript" src="js/show-password.js"></script>
    <script type="text/javascript" src="js/image-drag-disabler.js"></script>
    <script type="text/javascript" src="js/header-user-click.js"></script>